# Generated by Django 4.2.2 on 2023-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtranslations',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
