# Generated by Django 4.2.2 on 2023-06-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoping', '0002_item_name_itemtranslations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtranslations',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_translations', to='shoping.item'),
        ),
    ]
