# Generated by Django 4.2.2 on 2023-06-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoping', '0003_alter_itemtranslations_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoping.item'),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='shopping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoping.shopping'),
        ),
    ]
